CREATE TABLE `list_member` (
  `reportId` varchar(35) NOT NULL,
  `reportNo` varchar(20) NOT NULL,
  `clientId` varchar(35) NOT NULL,
  `clientName` varchar(20) NOT NULL,
  `gender` varchar(5) NOT NULL,
  `unit` varchar(40) NOT NULL,
  `age` numeric(3) NOT NULL,
  `reportDate` varchar(10) NOT NULL,
  `examinationOrgan` varchar(10),
  `company` varchar(40) NOT NULL,
  `grade` varchar(10) NOT NULL,
  `total` numeric(2) NOT NULL,
  `abnornmltotal` numeric(2) NOT NULL,
  PRIMARY KEY (`reportId`)
) ENGINE=InnoDB DEFAULT CHARSET=gbk;

CREATE TABLE `report_index` (
  `scientificName` varchar(30) NOT NULL,
  `reportName` varchar(30) NOT NULL,
  `genre` varchar(8) NOT NULL,
  PRIMARY KEY(`scientificName`)
) ENGINE=InnoDB DEFAULT CHARSET=gbk;

['血小板容积分布宽度（PDW）',
 '血小板比容（PCT）',
 '平均红细胞血红蛋白浓度（MCHC）',
 '平均红细胞体积（MCV）',
 '红细胞分布宽度变异系数(RDW-CV)',
 '平均红细胞血红蛋白含量（MCH）',
 '平均血小板体积（MPV）',
 '红细胞分布宽度标准差(RDW-SD)',
 '白细胞计数(WBC)',
 '红细胞计数(RBC)',
 '血小板(PLT)',
 '血红蛋白(Hb)',
 '红细胞比容(Hct)',
 '中性粒细胞百分比（NE%）',
 '中性粒细胞绝对数（NE#）',
 '淋巴细胞百分比（LY%）',
 '淋巴细胞绝对数（LY#）',
 '单核细胞百分比（MO%）',
 '单核细胞绝对数(MO#)',
 '嗜酸性粒细胞百分比（EO%）',
 '嗜酸性粒细胞绝对数(EO#)',
 '嗜碱性粒细胞百分比（BA%）',
 '嗜碱性粒细胞绝对数(BA#)',
 'reportId',
 'clientId',
 '血红蛋白[Hb]',
 '大血小板数目',
 '平均红细胞血红蛋白浓度[MCHC]',
 '单核细胞百分比[M]',
 '平均血小板体积[MPV]',
 '红细胞计数[RBC]',
 '淋巴细胞绝对值[L#]',
 '中性粒细胞绝对值[N#]',
 '红细胞体积分布宽度变异系数',
 '嗜碱性粒细胞百分比[BA%]',
 '大血小板比率[P-LCR]',
 '嗜酸性粒细胞绝对值[EO#]',
 '嗜碱性粒细胞绝对值[BA#]',
 '平均红细胞体积[MCV]',
 '血小板容积分布宽度[PDW]',
 '血小板计数(PLT)',
 '红细胞压积[HCT]',
 '单核细胞绝对值[M#]',
 '淋巴细胞百分比[L]',
 '平均血红蛋白含量[MCH]',
 '红细胞分布宽度标准差[RDW-SD]',
 '嗜酸性粒细胞百分比[EO%]',
 '血小板压积[PCT]',
 '中性粒细胞百分比[N]',
 '白细胞计数[WBC]',
 '血小板[PLT]',
 '嗜 碱性粒细胞绝对值(BASO#)',
 '嗜碱性粒细胞百分数（BASO%）',
 '嗜酸性粒细胞百分数（EOS%）',
 '中性粒细胞绝对值（NEU#）',
 '淋巴细胞绝对值（LYM#）',
 '嗜酸性粒细胞绝对值(EO#)',
 '单核细胞绝对值(MONO#)',
 '中性粒细胞百分比（NEU%）',
 '血红蛋白(HGB)',
 '淋巴细胞百分数（LYM%）',
 '单核细胞百分数（MONO%）',
 '红细胞压积(HCT)',
 '红细胞计数',
 '单核细胞比例',
 '血红蛋白浓度',
 '血红蛋白浓度(男)',
 '血小板计数',
 '血小板压积',
 '血小板体积分布宽度',
 '平均血小板体积',
 '大血小板比率',
 '网织红细胞计数',
 '单核细胞计数',
 '平均红细胞体积',
 '平均红细胞血红蛋白含量',
 '平均红细胞血红蛋白浓度',
 '红细胞分布宽度变异系数',
 '白细胞计数',
 '中性粒细胞比例',
 '中性粒细胞计数',
 '淋巴细胞比例',
 '淋巴细胞计数',
 '嗜酸性粒细胞比例',
 '嗜酸性粒细胞计数',
 '嗜碱性粒细胞比例',
 '嗜碱性粒细胞计数',
 '红细胞计数(男)',
 '红细胞计数(女)',
 '血红蛋白浓度(女)',
 '淋巴细胞百分率',
 '单核细胞百分率',
 '中性粒细胞百分率',
 '嗜酸性粒细胞百分率',
 '嗜碱性粒细胞百分率',
 '淋巴细胞绝对值',
 '单核细胞绝对值',
 '中性粒细胞绝对值',
 '嗜酸粒细胞绝对值',
 '嗜碱粒细胞绝对值',
 '血红蛋白',
 '红细胞压积',
 '平均血红蛋白含量',
 '红细胞体积分布宽度',
 '平均血红蛋白浓度',
 '淋巴细胞比值（LYM）',
 '单核细胞比值（MONO）',
 '嗜酸性粒细胞比值（EO）',
 '嗜碱性粒细胞比值（BASO）',
 '大血小板比率（P-LCR）',
 '中性粒细胞比值（GRA）',
 '中性粒细胞绝对值（GRA#）']